version: 2.1
orbs:
    node: circleci/node@3.0.0
workflows:
    build-test-deploy:
        jobs:
            - build-and-test-frontend
            - deploy-frontend:
                  requires:
                      - build-and-test-frontend
                  filters:
                      branches:
                          only:
                              - master
jobs:
    build-and-test-frontend:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages:
                  cache-path: node_modules
                  app-dir: .
            - run:
                  command: npm run format
                  name: Check for Formatting Errors
            - run:
                  command: npm run lint
                  name: Check for Linting Errors
            - run:
                  command: npm test
                  name: Run JavaScript Tests
            - run:
                  command: npm run build
                  name: Build JavaScript
            - persist_to_workspace:
                  root: ./
                  paths:
                      - prod
                      - node_modules
    deploy-frontend:
        executor:
            name: node/default
        steps:
            - attach_workspace:
                  at: ./
            - run:
                  name: Netlify Deploy
                  command: node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir prod
