version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
workflows:
  build-test-deploy:
    jobs:
      - build-and-test-frontend
      - build-and-test-server
      - deploy-frontend:
          requires:
            - build-and-test-frontend
          filters:
            branches:
              only:
                - master
      - deploy-backend:
          requires:
            - build-and-test-server
          filters:
            branches:
              only:
                - master

jobs:
  build-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: client/node_modules
          app-dir: client
      - run:
          command: npm run format
          name: Check for Formatting Errors
          working_directory: client
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: client
      - run:
          command: npm test
          name: Run JavaScript Tests
          working_directory: client
      - run:
          command: npm run build
          name: Build JavaScript
          working_directory: client
      - persist_to_workspace:
          root: ./
          paths:
            - client/prod
            - client/node_modules
  build-and-test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: server/node_modules
          app-dir: server
      - run:
          command: npm run format
          name: Check for Formatting Errors
          working_directory: server
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: server
      - run:
          command: npm test
          name: Run JavaScript Tests
          working_directory: server
      - run:
          command: npm run build
          name: Build JavaScript
          working_directory: server
      - persist_to_workspace:
          root: ./
          paths:
            - server/dist
            - server/node_modules
  deploy-frontend:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Netlify Deploy
          working_directory: client
          command: node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir prod
  deploy-backend:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
